//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int VaccinationId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> NumVaccination { get; set; }
    
        public virtual VaccineManufacturer VaccineManufacturer { get; set; }
        public virtual Member Member { get; set; }
    }
}
